name: CI/CD to Cloud Run from Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/benjaminbg/examenmlopsbbg:latest
          no-cache : true

      - name: Autenticarse con Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Desplegar en Cloud Run desde Docker Hub
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: examenmlopsbbg
          image: "docker.io/benjaminbg/examenmlopsbbg:latest"
          region: us-central1
