name: CI/CD to Cloud Run from Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_number }}
      IMAGE_NAME: benjaminbg/examenmlopsbbg
      IMAGE_REGISTRY: index.docker.io

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          no-cache: true

      - name: Autenticarse con Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Desplegar en Cloud Run desde imagen externa (sin mirror)
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: examenmlopsbbg
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          region: us-central1
